# Generated by Django 4.2.3 on 2023-07-10 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='time_interval',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.allowedtimeinterval', verbose_name='Промежуток времени для отправки'),
        ),
    ]
